spring.application.name=bankapp
spring.datasource.url=jdbc:mysql://localhost:3306/bankdetail
spring.datasource.username=root
spring.datasource.password=Your_password
spring.datasource.driver_class_name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
# secret key
jwt.secret=
# add secret key here 
spring.autoconfigure.exclude=SeurityAutoConfiguration
server.port=8081